# Start on push to main, or on a manual trigger
name: Auto Render
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    render:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
        - uses: actions/checkout@v4
        - name: Setup git
          run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "auto-render@github.com"
        - uses: actions-rust-lang/setup-rust-toolchain@v1
        - name: Install typst
          run: cargo install --locked typst-cli
        - name: Symlink library
          run: |
            mkdir -p ~/.local/share/typst/packages/local 
            ln -s $(pwd)/typst/physique ~/.local/share/typst/packages/local/physique
        - name: Run auto-render
          run: ./auto-render.sh