# Start on push to main, or on a manual trigger
name: Auto Render
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    render:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
        - uses: actions/checkout@v4
        - uses: actions-rust-lang/setup-rust-toolchain@v1
        - name: Install typst
          run: cargo install --locked typst-cli
        - name: Symlink library
          run: ln -s ./typst/physique ~/.local/share/typst/packages/local/physique
        - name: Run auto-render
          run: ./auto-render.sh